//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblUrunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUrunler()
        {
            this.TblSatıs = new HashSet<TblSatıs>();
        }
    
        public int UrunId { get; set; }
        [Required(ErrorMessage = "Bu alan zorunludur.")]
        public string UrunAd { get; set; }
        public string Marka { get; set; }
        public int UrunKategorı { get; set; }
        public Nullable<decimal> Fıyat { get; set; }
        public Nullable<byte> Stok { get; set; }
    
        public virtual TblKategorıler TblKategorıler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSatıs> TblSatıs { get; set; }
    }
}
